# Bluetooth name
CONFIG_ZMK_KEYBOARD_NAME="FoxyRVG34"
# Better bluetooth stability and connect via pin
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_PM_SOFT_OFF=y
CONFIG_ZMK_POINTING=y
# Enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
# Select WS2812 LED driver (most common)
CONFIG_WS2812_STRIP=y

# RGB underglow settings
CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

# 1.25ms multiplier for shortest time interval between updates 
# default is 6 but results in battery drain on Mac Sequoia)
# https://github.com/zmkfirmware/zmk/issues/2661
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
